/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Plugin: Equilibrium GOZ Engine for Obsidian
Author: Nelxson2099
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EquilibriumGOZPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var ZONES = [
  { id: 1, name: "Confort", color: "#6366F1", icon: "\u{1F3E0}", bg: "rgba(99, 102, 241, 0.15)" },
  { id: 2, name: "Miedo", color: "#EF4444", icon: "\u26A1", bg: "rgba(239, 68, 68, 0.15)" },
  { id: 3, name: "Aprendizaje", color: "#F59E0B", icon: "\u{1F9E0}", bg: "rgba(245, 158, 11, 0.15)" },
  { id: 4, name: "Crecimiento", color: "#10B981", icon: "\u{1F680}", bg: "rgba(16, 185, 129, 0.15)" }
];
var LEVELS = [
  { level: 1, minXP: 0, maxXP: 500, name: "Novicio", icon: "\u{1F331}", color: "#8892A4" },
  { level: 2, minXP: 500, maxXP: 1200, name: "Iniciado", icon: "\u{1F33F}", color: "#3B82F6" },
  { level: 3, minXP: 1200, maxXP: 2500, name: "Explorador", icon: "\u{1F9ED}", color: "#6366F1" },
  { level: 4, minXP: 2500, maxXP: 4500, name: "Desafiante", icon: "\u2694\uFE0F", color: "#8B5CF6" },
  { level: 5, minXP: 4500, maxXP: 7500, name: "Estratega", icon: "\u{1F6E1}\uFE0F", color: "#EC4899" },
  { level: 6, minXP: 7500, maxXP: 12e3, name: "Conquistador", icon: "\u{1F525}", color: "#F59E0B" },
  { level: 7, minXP: 12e3, maxXP: 18e3, name: "Campe\xF3n", icon: "\u{1F3C6}", color: "#10B981" },
  { level: 8, minXP: 18e3, maxXP: 25e3, name: "Tit\xE1n", icon: "\u{1F451}", color: "#06B6D4" },
  { level: 9, minXP: 25e3, maxXP: 35e3, name: "Leyenda", icon: "\u26A1", color: "#A855F7" },
  { level: 10, minXP: 35e3, maxXP: 5e4, name: "Trascendente", icon: "\u{1F31F}", color: "#F43F5E" }
];
var CONTEXTS = [
  { tag: "@ordenador", label: "Ordenador", color: "#10B981" },
  { tag: "@llamadas", label: "Llamadas", color: "#EF4444" },
  { tag: "@en_calle", label: "En Calle", color: "#F97316" },
  { tag: "@focus_modo", label: "Focus Modo", color: "#6366F1" },
  { tag: "@casa", label: "Casa", color: "#8B5CF6" }
];

// src/view.ts
var VIEW_TYPE_EQUILIBRIUM = "equilibrium-goz-view";
var EquilibriumGOZView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentTab = "dashboard";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_EQUILIBRIUM;
  }
  getDisplayText() {
    return "Equilibrium GOZ";
  }
  getIcon() {
    return "target";
  }
  async onOpen() {
    this.render();
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("goz-container");
    const data = this.plugin.data;
    const currentLevel = this.getLevelInfo(data.totalXP);
    const header = container.createEl("div", { cls: "goz-header-banner" });
    const levelInfo = header.createEl("div", { cls: "goz-level-info" });
    const badge = levelInfo.createEl("div", { cls: "goz-level-badge" });
    badge.createEl("span", { cls: "goz-level-icon", text: currentLevel.icon });
    const titleBox = badge.createEl("div");
    titleBox.createEl("div", { cls: "goz-level-title", text: `Nivel ${currentLevel.level} \u2014 ${currentLevel.name}` });
    titleBox.createEl("div", { cls: "goz-level-rank", text: `\u{1F525} Racha: ${data.streakDays} d\xEDas (Multiplicador Activo)` });
    levelInfo.createEl("div", { cls: "goz-xp-badge", text: `${data.totalXP.toLocaleString()} XP` });
    const progressBg = header.createEl("div", { cls: "goz-progress-bar-bg" });
    const progressFill = progressBg.createEl("div", { cls: "goz-progress-bar-fill" });
    const progressPct = Math.min(100, Math.max(5, data.totalXP / currentLevel.maxXP * 100));
    progressFill.style.width = `${progressPct}%`;
    const tabs = container.createEl("div", { cls: "goz-tabs" });
    const tabList = [
      { id: "dashboard", label: "\u{1F4CA} Dashboard" },
      { id: "gtd", label: `\u{1F4E5} GTD Inbox (${data.gtdTasks.filter((t) => t.status !== "completed").length})` },
      { id: "habitos", label: "\u{1F33F} H\xE1bitos" },
      { id: "expansion", label: "\u{1F680} Expansi\xF3n" }
    ];
    tabList.forEach((t) => {
      const btn = tabs.createEl("button", {
        cls: `goz-tab-btn ${this.currentTab === t.id ? "active" : ""}`,
        text: t.label
      });
      btn.onclick = () => {
        this.currentTab = t.id;
        this.render();
      };
    });
    const content = container.createEl("div");
    if (this.currentTab === "dashboard") {
      this.renderDashboard(content, data);
    } else if (this.currentTab === "gtd") {
      this.renderGTD(content, data);
    } else if (this.currentTab === "habitos") {
      this.renderHabits(content, data);
    } else if (this.currentTab === "expansion") {
      this.renderExpansionLog(content, data);
    }
  }
  getLevelInfo(xp) {
    for (let i = LEVELS.length - 1; i >= 0; i--) {
      if (xp >= LEVELS[i].minXP) return LEVELS[i];
    }
    return LEVELS[0];
  }
  renderDashboard(el, data) {
    const grid = el.createEl("div", { cls: "goz-zones-grid" });
    ZONES.forEach((zone) => {
      const count = data.activities.filter((a) => a.zona_id === zone.id).length;
      const card = grid.createEl("div", { cls: "goz-zone-card" });
      card.style.borderColor = `${zone.color}40`;
      const cardHeader = card.createEl("div", { cls: "goz-zone-header" });
      cardHeader.createEl("span", { text: `${zone.icon} ${zone.name}`, attr: { style: `color: ${zone.color}; font-weight: 700;` } });
      cardHeader.createEl("span", { cls: "goz-zone-count", text: `${count}`, attr: { style: `color: ${zone.color};` } });
      card.createEl("p", { text: `Expansiones registradas en ${zone.name}`, attr: { style: "font-size: 11px; opacity: 0.7;" } });
    });
    el.createEl("h3", { text: "\u26A1 \xDAltimas Expansiones Registradas" });
    if (data.activities.length === 0) {
      el.createEl("p", { text: "A\xFAn no has registrado actividades. \xA1Haz un registro en la pesta\xF1a Expansi\xF3n!", attr: { style: "opacity: 0.6;" } });
    } else {
      data.activities.slice(-5).reverse().forEach((act) => {
        const zone = ZONES.find((z) => z.id === act.zona_id) || ZONES[0];
        const item = el.createEl("div", { cls: "goz-task-item" });
        item.style.borderLeft = `4px solid ${zone.color}`;
        item.createEl("span", { text: `${zone.icon} ${act.descripcion}` });
        item.createEl("span", { text: new Date(act.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }), attr: { style: "font-size: 11px; opacity: 0.6;" } });
      });
    }
    const backupBtn = el.createEl("button", { cls: "goz-btn-primary", text: "\u{1F4BE} Exportar Respaldo JSON" });
    backupBtn.style.marginTop = "20px";
    backupBtn.onclick = () => {
      const jsonStr = JSON.stringify(data, null, 2);
      navigator.clipboard.writeText(jsonStr);
      new import_obsidian.Notice("\xA1Respaldo JSON copiado al portapapeles con \xE9xito!");
    };
  }
  renderGTD(el, data) {
    const box = el.createEl("div", { cls: "goz-gtd-box" });
    box.createEl("h4", { text: "\u26A1 Captura R\xE1pida de Tarea (Inbox GTD)" });
    const inputGroup = box.createEl("div", { cls: "goz-input-group" });
    const input = inputGroup.createEl("input", { cls: "goz-input", attr: { placeholder: "Escribe tu tarea o idea..." } });
    const addBtn = inputGroup.createEl("button", { cls: "goz-btn-primary", text: "+ Capturar" });
    let selectedContext = CONTEXTS[0].tag;
    const chips = box.createEl("div", { cls: "goz-context-chips" });
    CONTEXTS.forEach((c) => {
      const chip = chips.createEl("span", { cls: "goz-chip", text: c.tag });
      chip.style.backgroundColor = `${c.color}20`;
      chip.style.color = c.color;
      chip.onclick = () => {
        selectedContext = c.tag;
        new import_obsidian.Notice(`Contexto seleccionado: ${c.tag}`);
      };
    });
    const addGTD = () => {
      const val = input.value.trim();
      if (!val) return;
      const newTask = {
        id: Date.now().toString(),
        title: val,
        context: selectedContext,
        zona_id: 1,
        status: "inbox",
        createdAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      data.gtdTasks.push(newTask);
      this.plugin.savePluginData();
      new import_obsidian.Notice("\xA1Tarea capturada al Inbox!");
      input.value = "";
      this.render();
    };
    addBtn.onclick = addGTD;
    input.onkeydown = (e) => {
      if (e.key === "Enter") addGTD();
    };
    el.createEl("h3", { text: "\u{1F4E5} Bandeja de Entrada" });
    const pending = data.gtdTasks.filter((t) => t.status !== "completed");
    if (pending.length === 0) {
      el.createEl("p", { text: "\xA1Inbox totalmente despejado! \u{1F680}", attr: { style: "opacity: 0.6;" } });
    } else {
      pending.forEach((t) => {
        const item = el.createEl("div", { cls: "goz-task-item" });
        item.createEl("span", { text: `${t.title} (${t.context})` });
        const completeBtn = item.createEl("button", { cls: "goz-btn-primary", text: "\u2713 Completar" });
        completeBtn.style.padding = "4px 10px";
        completeBtn.style.fontSize = "11px";
        completeBtn.onclick = () => {
          t.status = "completed";
          data.totalXP += 100;
          this.plugin.savePluginData();
          new import_obsidian.Notice("\xA1Tarea completada! +100 XP");
          this.render();
        };
      });
    }
  }
  renderHabits(el, data) {
    el.createEl("h3", { text: "\u{1F33F} H\xE1bitos & Rutinas" });
    if (data.habits.length === 0) {
      data.habits = [
        { id: "h1", title: "Lectura Zettelkasten / Obsidian", frequency: "daily", zona_id: 3, streak: 3, completedPeriods: [] },
        { id: "h2", title: "Entrenamiento F\xEDsico", frequency: "daily", zona_id: 4, streak: 5, completedPeriods: [] },
        { id: "h3", title: "Revisi\xF3n de Proyectos & Metas", frequency: "weekly", zona_id: 4, streak: 2, completedPeriods: [] }
      ];
      this.plugin.savePluginData();
    }
    data.habits.forEach((h) => {
      const card = el.createEl("div", { cls: "goz-habit-card" });
      const info = card.createEl("div");
      info.createEl("div", { text: h.title, attr: { style: "font-weight: 700;" } });
      info.createEl("div", { text: `Frecuencia: ${h.frequency.toUpperCase()} | \u{1F525} Racha: ${h.streak} per\xEDodos`, attr: { style: "font-size: 11px; opacity: 0.7;" } });
      const btn = card.createEl("button", { cls: "goz-habit-btn", text: "Marcar Cumplido" });
      btn.onclick = () => {
        h.streak += 1;
        data.totalXP += 150;
        this.plugin.savePluginData();
        new import_obsidian.Notice(`\xA1H\xE1bito marcado! \u{1F525} Racha: ${h.streak} | +150 XP`);
        this.render();
      };
    });
  }
  renderExpansionLog(el, data) {
    const box = el.createEl("div", { cls: "goz-gtd-box" });
    box.createEl("h4", { text: "\u{1F680} Registrar Nueva Expansi\xF3n" });
    const inputDesc = box.createEl("input", { cls: "goz-input", attr: { placeholder: "\xBFQu\xE9 zona desafiaste hoy?" } });
    inputDesc.style.marginBottom = "10px";
    const selectZone = box.createEl("select", { cls: "goz-input" });
    selectZone.style.marginBottom = "10px";
    ZONES.forEach((z) => {
      const opt = selectZone.createEl("option", { text: `${z.icon} Zona de ${z.name}` });
      opt.value = z.id.toString();
    });
    const submitBtn = box.createEl("button", { cls: "goz-btn-primary", text: "Registrar Expansi\xF3n" });
    submitBtn.onclick = () => {
      const desc = inputDesc.value.trim();
      if (!desc) return;
      const newAct = {
        id: Date.now().toString(),
        zona_id: parseInt(selectZone.value),
        descripcion: desc,
        resistencia: 3,
        habilidad: 4,
        meta_cumplida: true,
        timestamp: (/* @__PURE__ */ new Date()).toISOString()
      };
      data.activities.push(newAct);
      data.totalXP += 250;
      data.streakDays += 1;
      this.plugin.savePluginData();
      new import_obsidian.Notice("\xA1Expansi\xF3n registrada con \xE9xito! +250 XP \u{1F680}");
      this.render();
    };
  }
};

// src/main.ts
var DEFAULT_DATA = {
  activities: [],
  gtdTasks: [],
  habits: [],
  totalXP: 8725,
  streakDays: 7,
  lastActiveDate: (/* @__PURE__ */ new Date()).toISOString(),
  leisurePoints: 16
};
var EquilibriumGOZPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.data = DEFAULT_DATA;
  }
  async onload() {
    await this.loadPluginData();
    this.registerView(
      VIEW_TYPE_EQUILIBRIUM,
      (leaf) => new EquilibriumGOZView(leaf, this)
    );
    this.addRibbonIcon("target", "Equilibrium GOZ", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-equilibrium-goz-view",
      name: "Abrir Panel Equilibrium GOZ",
      callback: () => {
        this.activateView();
      }
    });
    console.log("Equilibrium GOZ Engine Plugin cargado exitosamente.");
  }
  async onunload() {
    console.log("Equilibrium GOZ Engine Plugin descargado.");
  }
  async loadPluginData() {
    this.data = Object.assign({}, DEFAULT_DATA, await this.loadData());
  }
  async savePluginData() {
    await this.saveData(this.data);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_EQUILIBRIUM);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({
        type: VIEW_TYPE_EQUILIBRIUM,
        active: true
      }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
};
